openapi: 3.0.0

info:
  description: "This is description of Platform API"
  version: "1.0.0"
  title: "Platform service API"

servers:
  - url: http://localhost:8080/{basePath}/
    variables:
      basePath:
        default: platform/api/v1

tags:
  - name: "Category"
  - name: "Language"
  - name: "City"

paths:
  /category/roots:
    get:
      summary: Return list of root categories
      tags:
        - "Category"
      description: Return the list of all root categories
      operationId: getRootsCategories
      parameters:
        - in: header
          name: Locale-code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Request is proceded successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'


  /category/{categoryId}:
    get:
      summary: Retriving category by id
      operationId: getById
      tags:
        - "Category"
      parameters:
        - name: "categoryId"
          in: "path"
          description: "Category id"
          required: true
          schema:
            type: integer
        - in: header
          name: Locale-code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Request is proceded successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'
        "204":
          description: The category by id was not found.

  /city/all:
    get:
      summary: List of cities in country
      operationId: getAllCitiesInCountry
      tags:
        - "City"
      parameters:
        - name: "countryIsoCode"
          in: "query"
          description: "Iso-code of country"
          required: true
          schema:
            type: string
        - in: header
          name: Locale-code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Request is proceded successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CityDto'

  /language/all:
    get:
      summary: List of languages which avaialble in a country
      operationId: getAllLanguagesInCountry
      tags:
        - "Language"
      parameters:
        - name: "countryIsoCode"
          in: "query"
          description: "Iso-code of country"
          required: true
          schema:
            type: string
        - in: header
          name: Locale-code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Request is proceded successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LanguageDto'

components:
  schemas:
    CategoryDto:
      description: Category tree
      type: object
      required:
        - id
        - title
      properties:
        id:
          description: unique identifier of category id
          type: integer
        title:
          description: the name of category
          type: string
        parent:
          description: unique identifier of parent category id
          type: integer
        children:
          description: the list of children category
          type: array
          items:
            $ref: integer
    CityDto:
      description: The DTO object of a city
      type: object
      required:
        - title
      properties:
        title:
          description: the title of a language
          type: string

    LanguageDto:
      description: The DTO object of a language
      type: object
      required:
        - isoCode
        - title
      properties:
        isoCode:
          description: the iso-code of a language
          type: string
        title:
          description: the title of a language
          type: string
